-- PEYVAND SECURITY HARDENING
-- Run this migration in the Peyvand Supabase SQL Editor.
-- It does not change passwords or Auth provider settings.

create table if not exists public.peyvand_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.peyvand_audit_logs enable row level security;

revoke all on public.peyvand_audit_logs from anon;
grant select on public.peyvand_audit_logs to authenticated;

drop policy if exists "audit_owner_select" on public.peyvand_audit_logs;
create policy "audit_owner_select"
on public.peyvand_audit_logs
for select
to authenticated
using (public.peyvand_has_role(array['owner']));

create or replace function public.peyvand_write_audit(
  p_action text,
  p_target_user_id uuid default null,
  p_target_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.peyvand_audit_logs(actor_user_id,target_user_id,target_id,action,details)
  values(auth.uid(),p_target_user_id,p_target_id,p_action,coalesce(p_details,'{}'::jsonb));
end;
$$;

revoke execute on function public.peyvand_write_audit(text,uuid,text,jsonb) from public;
grant execute on function public.peyvand_write_audit(text,uuid,text,jsonb) to authenticated;

-- Server-side identity enforcement: the browser can never choose another employee's name/number.
create or replace function public.peyvand_secure_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  e public.peyvand_employees%rowtype;
begin
  select * into e
  from public.peyvand_employees
  where user_id = auth.uid()
    and is_active = true;

  if e.id is null then
    raise exception 'دسترسی حساب فعال نیست';
  end if;

  if new.room <> 'general' then
    raise exception 'اتاق نامعتبر است';
  end if;

  new.name := e.full_name;
  new.employee := e.employee_number;
  new.message := btrim(new.message);

  if length(new.message) = 0 or length(new.message) > 2000 then
    raise exception 'طول پیام نامعتبر است';
  end if;

  return new;
end;
$$;

drop trigger if exists peyvand_secure_message_trigger on public.peyvand_messages;
create trigger peyvand_secure_message_trigger
before insert on public.peyvand_messages
for each row execute function public.peyvand_secure_message();

-- Basic anti-spam protection: max 5 messages per 10 seconds per authenticated user.
-- Uses auth.uid() directly so the browser cannot influence the rate-limit identity.
create or replace function public.peyvand_message_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'احراز هویت الزامی است';
  end if;

  if (
    select count(*)
    from public.peyvand_messages m
    join public.peyvand_employees e on e.employee_number = m.employee
    where e.user_id = auth.uid()
      and m.created_at > now() - interval '10 seconds'
  ) >= 5 then
    raise exception 'تعداد پیام‌ها بیش از حد مجاز است. چند ثانیه صبر کنید.';
  end if;

  return new;
end;
$$;

drop trigger if exists peyvand_message_rate_limit_trigger on public.peyvand_messages;
create trigger peyvand_message_rate_limit_trigger
before insert on public.peyvand_messages
for each row execute function public.peyvand_message_rate_limit();

-- Audit message creation/deletion.
create or replace function public.peyvand_audit_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.peyvand_write_audit(
      'message_created', auth.uid(), new.id::text,
      jsonb_build_object('room',new.room)
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.peyvand_write_audit(
      'message_deleted', auth.uid(), old.id::text,
      jsonb_build_object('room',old.room,'employee',old.employee)
    );
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists peyvand_audit_message_trigger on public.peyvand_messages;
create trigger peyvand_audit_message_trigger
after insert or delete on public.peyvand_messages
for each row execute function public.peyvand_audit_message();

-- Audit account activation/deactivation and role changes.
create or replace function public.peyvand_audit_employee_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.is_active is distinct from new.is_active then
    perform public.peyvand_write_audit(
      case when new.is_active then 'user_activated' else 'user_blocked' end,
      auth.uid(), new.user_id::text,
      jsonb_build_object('target_user_id',new.user_id,'employee_number',new.employee_number)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists peyvand_audit_employee_trigger on public.peyvand_employees;
create trigger peyvand_audit_employee_trigger
after update on public.peyvand_employees
for each row execute function public.peyvand_audit_employee_change();

create or replace function public.peyvand_audit_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.peyvand_write_audit(
      'role_created', auth.uid(), new.user_id::text,
      jsonb_build_object('role',new.role)
    );
    return new;
  elsif tg_op = 'UPDATE' and old.role is distinct from new.role then
    perform public.peyvand_write_audit(
      'role_changed', auth.uid(), new.user_id::text,
      jsonb_build_object('from',old.role,'to',new.role)
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.peyvand_write_audit(
      'role_deleted', auth.uid(), old.user_id::text,
      jsonb_build_object('role',old.role)
    );
    return old;
  end if;
  return coalesce(new,old);
end;
$$;

drop trigger if exists peyvand_audit_role_trigger on public.peyvand_user_roles;
create trigger peyvand_audit_role_trigger
after insert or update or delete on public.peyvand_user_roles
for each row execute function public.peyvand_audit_role_change();

create index if not exists peyvand_audit_logs_created_at_idx
on public.peyvand_audit_logs(created_at desc);

create index if not exists peyvand_audit_logs_actor_idx
on public.peyvand_audit_logs(actor_user_id);

create index if not exists peyvand_audit_logs_target_idx
on public.peyvand_audit_logs(target_user_id);

create unique index if not exists peyvand_employees_phone_unique_idx
on public.peyvand_employees(phone)
where phone is not null;

-- Tighten message policies: identity is supplied by the database trigger, not the browser.
drop policy if exists "peyvand_messages_insert_secure" on public.peyvand_messages;
create policy "peyvand_messages_insert_secure"
on public.peyvand_messages
for insert
to authenticated
with check (
  room = 'general'
  and exists (
    select 1 from public.peyvand_employees e
    where e.user_id = auth.uid() and e.is_active = true
  )
);

-- Audit table must not be directly writable by clients.
revoke insert, update, delete on public.peyvand_audit_logs from authenticated;
